archive.dir=E:\\Muzica\\Romania Hip-Hop\\2012

service.location=http://localhost:8080
play.service=http://localhost:8080/listen
img.service=http://localhost:8080/cover

default.cover=src/main/resources/static/assets/img/retro.png




